[[redirects]]
from = "/blogs/*"
to = "https://an-horse-blogs.netlify.app/blogs/:splat"
status = 200

[[redirects]]
from = "/teaches/python/*"
to = "https://an-horse-teaches-python.netlify.app/teaches/python/:splat"
status = 200

[[redirects]]
from = "/teaches/java/*"
to = "https://an-horse-teaches-java.netlify.app/teaches/java/:splat"
status = 200
